### PR TITLE
introduce halt_chain

### PR DESCRIPTION
**Pull request by apneadiving**

### CODE REVIEW

**Comment by apneadiving** [comment]
@RasMachineMan could you please confirm naming is fine to you?

**Comment by RasMachineMan** [comment]
Halt chain clear as a tear. Usage is confusing me though. Where would I use it though ? I understand that you can return from the chain at any given moment. Is it correct ? Why then halt chain has to be the last command in the chain ? I thought it should be somewhere between chains. Send me a use  case.

**Comment by apneadiving** [comment]
`halt_chain` returns what the block returns, not `self`. So it cannot be chained anymore.

The usage is for instance if you create a method in a model which calls a wf. You want the method to return a value, you dont want it to be a wf.

```ruby
def create_user
  Flow.new
    .chain(user: :user) { Services::User::Create.new(params) }
    .halt_flow do |outflow, error_pool|
      if error_pool
        raise 
      else
        outflow.user
      end
    end
```

I basically need this for graphql: there is a resolve method which takes a block and is waiting for a return value (no render like in controllers)

**Comment by RasMachineMan** [comment]
Okey, it makes more sense. You should give an example with Graphqllleeeee too ;)

**Comment by apneadiving** [comment]
halt_flow reads good...

**Comment by RasMachineMan** [comment]
I like them both, but there is chain to chain actions, so you should follow halt_chain to stop it.

**Comment by apneadiving** [comment]
I wonder if halt_chain would make people believe it only works when not dammed.
Halt_flow may be clearer for this

Benjamin

**Comment by RasMachineMan** [comment]
Didn't think about it this way, but now as you have mentioned it I don't think it will make a difference.

**Pull request merged**
